### ISSUE TITLE
SPTextUtil.hasSPINRDF() prohibits Commands with non-SPIN properties

### ISSUE THREAD

**Issue by pumba-lt** [spinrdf/spinrdf#2]
This [condition](../blob/master/src/main/java/org/spinrdf/util/SPTextUtil.java#L181)

    if(!RDF.type.equals(o.getPredicate()) && !SP.text.equals(o.getPredicate()) && !SPIN.thisUnbound.equals(o.getPredicate()))

checks whether a command has SPIN RDF attached, but also prevents commands from having additional properties.

I think a proper solution would be to move this code from the util class into a `Command.hasSPINRDF()` method, which would be implemented differently by subclasses such as `Ask`, `Construct` etc. They could check the existence of "root" properties such as `sp:where` based on the [SPIN SPARQL Syntax](http://spinrdf.org/sp.html).

If we agree, I will try to make a PR.

**Comment by HolgerKnublauch** [comment]
Sounds good to me.

**Comment by pumba-lt** [comment]
On a second thought, maybe testing for individual properties is an overkill... What about simply testing for properties from the SP namespace (except `sp:text`)?

    if (SP.NS.equals(o.getPredicate().getNameSpace()) && !SP.text.equals(o.getPredicate())
        return true;

That would have the same effect I think?

**Comment by HolgerKnublauch** [comment]
Wouldn't it be enough to just test for sp:where?

**Comment by pumba-lt** [comment]
But what about cases such as [Load](http://spinrdf.org/sp.html#sp-Load)? It does not have `sp:where`, but has other `sp:` properties:

    [ a       sp:Load ;
      sp:document <http://example.org> ;
      sp:into <http://target.org>
    ]
